### PR TITLE
Bump DDS to 3.5.13

### PR DESCRIPTION
**Pull request by AndreyLebedev**
* Also temporarily comment out bottles which will be generated later

### CODE REVIEW

**Comment by dennisklein** [comment]
hmm, does this work for you? for me the patch does not work for 3.5.13

**Comment by AndreyLebedev** [comment]
sorry, no it doesn't, it fails to apply a patch, need more time to get it right

**Comment by dennisklein** [comment]
It is this patch: FairRootGroup/DDS#354. Needs just a rebase on current master. If it is not merged upstream any time soon, we can keep hosting the patch in the FairSoft repo, we have the `patches/` subdirectory especially for such situations, see https://github.com/FairRootGroup/FairSoft/tree/master/patches.

**Comment by dennisklein** [comment]
@AndreyLebedev So, the DDS Formula is now bumped to 3.5.14 and installed on `citmac001` and `witmac007`, but when running the FairRootGroup/ODC#18 test suite, [it complains about](https://alfa-ci.gsi.de/blue/rest/organizations/jenkins/pipelines/FairRootGroup/pipelines/ODC/branches/PR-18/runs/6/log/?start=0)
```
test 23
      Start 23: odc_core_lib::topology/construction

23: Test command: /Users/alfaci/alfaci/workspace/FairRootGroup_ODC_PR-18/build/tests/odc_core_lib-tests "--log_level=message" "--run_test=topology/construction" "--" "--topo-file" "/Users/alfaci/alfaci/workspace/FairRootGroup_ODC_PR-18/build/install/share/odc/odc_core_lib-tests-topo.xml"
23: Environment variables: 
23:  DYLD_LIBRARY_PATH=/Users/alfaci/alfaci/workspace/FairRootGroup_ODC_PR-18/build/install/lib:$DYLD_LIBRARY_PATH
23:  PATH=/Users/alfaci/alfaci/workspace/FairRootGroup_ODC_PR-18/build/install/bin:$PATH
23: Test timeout computed to be: 10
23: Running 1 test case...
23: Creating new worker package...
23: WN Package Tool: failed; STDOUT:; STDERR: env: bash: No such file or directory
23: 
 1/33 Test #28: odc_core_lib::topology/set_properties .......................................***Timeout  10.03 sec
Running 1 test case...
Creating new worker package...
WN Package Tool: failed; STDOUT:; STDERR: env: bash: No such file or directory
```

Not really sure if this is a problem of the DDS installation or if I am missing setting something up.

**Comment by dennisklein** [comment]
Nevermind, the moment I posted this, I realized that I have missed the `ENV` in the ctest environment variable declaration which was there before my change... works now :P

**Comment by dennisklein** [comment]
closing because obsolete

**Pull request closed without merging**
