### PR TITLE
Update fairsoft

### PR DESCRIPTION
**Pull request by rbx**
- Update FairSoft version to jav24.
- ~~Have only a single FairSoft recipe, for the latest release~~ Remove fairsoft alias - the new jan24 formula now has that name.

### CODE REVIEW

**Comment by rbx** [comment]
This installed fine.
I'll check if it plays together with the other packages.

**Comment by dennisklein** [comment]
Technically, we should disable the old formulas for a while, so if people would find old docs, they could get a message that we have transitioned away from the versioned formulas or so?

**Comment by dennisklein** [comment]
Check https://docs.brew.sh/Deprecating-Disabling-and-Removing-Formulae

**Comment by dennisklein** [comment]
I would expect you can just keep the versioned formulas for now together with the new unversioned. The only thing to delete would be the alias. But I have never tried it in this combo.

**Review by dennisklein — APPROVED** [review]

**Pull request merged**
